language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./src/ --standard=PSR1 --encoding=utf-8 --report=summary
  - php vendor/bin/phpcs ./src/ --standard=PSR2 --encoding=utf-8 --report=summary
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=.reports/clover.xml